controller_list:
  - name: fake_manipulator_controller
    joints:
      - rail_base_to_carrier
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
  - name: fake_rotation_table_controller
    joints:
      - table_base_to_table